-- IDs are UUID strings generated by the client (Android) or server.
-- updated_at drives last-write-wins conflict resolution in sync.
-- deleted_at = soft delete; records are never purged so clients can detect removals.

CREATE TABLE IF NOT EXISTS decks (
    id          TEXT        PRIMARY KEY,
    user_id     TEXT        NOT NULL,
    name        TEXT        NOT NULL,
    description TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_decks_user_updated ON decks (user_id, updated_at);

CREATE TABLE IF NOT EXISTS cards (
    id               TEXT             PRIMARY KEY,
    deck_id          TEXT             NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    user_id          TEXT             NOT NULL,
    front            TEXT             NOT NULL,
    back             TEXT             NOT NULL,
    interval         INTEGER          NOT NULL DEFAULT 1,
    ease_factor      DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    repetitions      INTEGER          NOT NULL DEFAULT 0,
    next_review_time TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_cards_user_updated ON cards (user_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_cards_deck         ON cards (deck_id);
