// Code generated from android DefaultSeedData.kt. DO NOT EDIT.
// Regenerate with: python3 backend/scripts/gen_seed.py
package seed

// seedCardData holds the shared Catalan front and its per-language translation.
type seedCardData struct {
	Front, En, Es, Ru string
}

// seedDeckData is one default deck (one per UI language).
type seedDeckData struct {
	Language, Name string
}

var seedDecks = []seedDeckData{
	{"en", "Basic Catalan"},
	{"es", "Catalán básico"},
	{"ru", "Базовый каталанский"},
}

var seedCards = []seedCardData{
	{"Hola", "Hello", "Hola", "Привет"},
	{"Adiós", "Goodbye", "Adiós", "До свидания"},
	{"A reveure", "See you again", "Hasta pronto", "До встречи"},
	{"Fins aviat", "See you soon", "Hasta pronto", "До скорого"},
	{"Gràcies", "Thank you", "Gracias", "Спасибо"},
	{"Bé", "Good", "Bien", "Хорошо"},
	{"Malament", "Bad", "Mal", "Плохо"},
	{"Si us plau", "Please", "Por favor", "Пожалуйста"},
	{"Sí", "Yes", "Sí", "Да"},
	{"No", "No", "No", "Нет"},
	{"Bon dia", "Good morning", "Buenos días", "Доброе утро"},
	{"Bona tarda", "Good afternoon", "Buenas tardes", "Добрый день"},
	{"Bona nit", "Good night", "Buenas noches", "Добрый вечер"},
	{"Matí", "Morning", "Mañana", "Утро"},
	{"Tarda", "Afternoon", "Tarde", "День"},
	{"Vespre", "Evening", "Tarde", "Вечер"},
	{"Nit", "Night", "Noche", "Ночь"},
	{"Perdona", "Excuse me", "Perdona", "Извините"},
	{"Ho sento", "Sorry", "Lo siento", "Простите"},
	{"Com estàs?", "How are you?", "¿Cómo estás?", "Как дела?"},
	{"Molt bé", "Very well", "Muy bien", "Очень хорошо"},
	{"Què?", "What?", "¿Qué?", "Что?"},
	{"On?", "Where?", "¿Dónde?", "Где?"},
	{"Quan?", "When?", "¿Cuándo?", "Когда?"},
	{"Per què?", "Why?", "¿Por qué?", "Почему?"},
	{"Qui?", "Who?", "¿Quién?", "Кто?"},
	{"Com?", "How?", "¿Cómo?", "Как?"},
	{"Quant?", "How much?", "¿Cuánto?", "Сколько?"},
	{"No entenc", "I don't understand", "No entiendo", "Не понимаю"},
	{"Repetiu, si us plau", "Please repeat", "Repita, por favor", "Повторите"},
	{"On és...?", "Where is...?", "¿Dónde está...?", "Где находится...?"},
	{"Quant costa?", "How much is it?", "¿Cuánto cuesta?", "Сколько стоит?"},
	{"Jo soc...", "I am...", "Yo soy...", "Я..."},
	{"Tu ets...", "You are...", "Tú eres...", "Ты..."},
	{"Ell és...", "He is...", "Él es...", "Он..."},
	{"Ella és...", "She is...", "Ella es...", "Она..."},
	{"Nosaltres som...", "We are...", "Nosotros somos...", "Мы..."},
	{"Vosaltres sou...", "You (plural) are...", "Vosotros sois...", "Вы (множ.)..."},
	{"Ells són...", "They are...", "Ellos son...", "Они..."},
	{"Vull", "I want", "Quiero", "Хочу"},
	{"Puc", "I can", "Puedo", "Могу"},
	{"Tinc", "I have", "Tengo", "Имею"},
	{"Sé", "I know", "Sé", "Знаю"},
	{"Naixement", "Birth", "Nacimiento", "Рождение"},
	{"Tinc ... anys", "I am ... years old", "Tengo ... años", "Мне ... лет"},
	{"Quants anys tens?", "How old are you?", "¿Cuántos años tienes?", "Сколько тебе лет?"},
	{"Em desperto", "I wake up", "Me despierto", "Просыпаюсь"},
	{"Em vaig a dormir", "I go to sleep", "Me voy a dormir", "Ложусь спать"},
	{"Un", "One", "Uno", "Один"},
	{"Dos", "Two", "Dos", "Два"},
	{"Tres", "Three", "Tres", "Три"},
	{"Quatre", "Four", "Cuatro", "Четыре"},
	{"Cinc", "Five", "Cinco", "Пять"},
	{"Sis", "Six", "Seis", "Шесть"},
	{"Set", "Seven", "Siete", "Семь"},
	{"Vuit", "Eight", "Ocho", "Восемь"},
	{"Nou", "Nine", "Nueve", "Девять"},
	{"Deu", "Ten", "Diez", "Десять"},
	{"Onze", "Eleven", "Once", "Одиннадцать"},
	{"Dotze", "Twelve", "Doce", "Двенадцать"},
	{"Tretze", "Thirteen", "Trece", "Тринадцать"},
	{"Catorze", "Fourteen", "Catorce", "Четырнадцать"},
	{"Quinze", "Fifteen", "Quince", "Пятнадцать"},
	{"Setze", "Sixteen", "Dieciséis", "Шестнадцать"},
	{"Disset", "Seventeen", "Diecisiete", "Семнадцать"},
	{"Divuit", "Eighteen", "Dieciocho", "Восемнадцать"},
	{"Dinou", "Nineteen", "Diecinueve", "Девятнадцать"},
	{"Vint", "Twenty", "Veinte", "Двадцать"},
	{"Cent", "Hundred", "Cien", "Сто"},
	{"Mil", "Thousand", "Mil", "Тысяча"},
	{"Gener", "January", "Enero", "Январь"},
	{"Febrer", "February", "Febrero", "Февраль"},
	{"Març", "March", "Marzo", "Март"},
	{"Abril", "April", "Abril", "Апрель"},
	{"Maig", "May", "Mayo", "Май"},
	{"Juny", "June", "Junio", "Июнь"},
	{"Juliol", "July", "Julio", "Июль"},
	{"Agost", "August", "Agosto", "Август"},
	{"Setembre", "September", "Septiembre", "Сентябрь"},
	{"Octubre", "October", "Octubre", "Октябрь"},
	{"Novembre", "November", "Noviembre", "Ноябрь"},
	{"Desembre", "December", "Diciembre", "Декабрь"},
	{"Dilluns", "Monday", "Lunes", "Понедельник"},
	{"Dimarts", "Tuesday", "Martes", "Вторник"},
	{"Dimecres", "Wednesday", "Miércoles", "Среда"},
	{"Dijous", "Thursday", "Jueves", "Четверг"},
	{"Divendres", "Friday", "Viernes", "Пятница"},
	{"Dissabte", "Saturday", "Sábado", "Суббота"},
	{"Diumenge", "Sunday", "Domingo", "Воскресенье"},
	{"Hora", "Hour", "Hora", "Час"},
	{"Minut", "Minute", "Minuto", "Минута"},
	{"Segon", "Second", "Segundo", "Секунда"},
	{"Avui", "Today", "Hoy", "Сегодня"},
	{"Ara", "Now", "Ahora", "Сейчас"},
	{"Temps", "Time", "Tiempo", "Время"},
	{"Home", "Man", "Hombre", "Мужчина"},
	{"Dona", "Woman", "Mujer", "Женщина"},
	{"Nena", "Girl", "Niña", "Девочка"},
	{"Nen", "Boy", "Niño", "Мальчик"},
	{"Mare", "Mother", "Madre", "Мама"},
	{"Pare", "Father", "Padre", "Папа"},
	{"Germà", "Brother", "Hermano", "Брат"},
	{"Germana", "Sister", "Hermana", "Сестра"},
	{"Fill", "Son", "Hijo", "Сын"},
	{"Filla", "Daughter", "Hija", "Дочь"},
	{"Marit", "Husband", "Marido", "Муж"},
	{"Muller", "Wife", "Esposa", "Жена"},
	{"Gat", "Cat", "Gato", "Кот"},
	{"Gos", "Dog", "Perro", "Собака"},
	{"Conill", "Rabbit", "Conejo", "Кролик"},
	{"Llebre", "Hare", "Liebre", "Заяц"},
	{"Rata", "Rat", "Rata", "Крыса"},
	{"Ratolí", "Mouse", "Ratón", "Мышь"},
	{"Casa", "House", "Casa", "Дом"},
	{"Cuina", "Kitchen", "Cocina", "Кухня"},
	{"Saló", "Living room", "Salón", "Зал"},
	{"Pis", "Floor", "Piso", "Этаж"},
	{"Terra", "Floor", "Suelo", "Пол"},
	{"Sostre", "Ceiling", "Techo", "Потолок"},
	{"Teulada", "Roof", "Tejado", "Крыша"},
	{"Carrer", "Street", "Calle", "Улица"},
	{"Avinguda", "Avenue", "Avenida", "Проспект"},
	{"Parada", "Stop", "Parada", "Остановка"},
	{"Autobús", "Bus", "Autobús", "Автобус"},
	{"Metro", "Metro", "Metro", "Метро"},
	{"Tren", "Train", "Tren", "Поезд"},
	{"Bicicleta", "Bicycle", "Bicicleta", "Велосипед"},
	{"Cotxe", "Car", "Coche", "Машина"},
	{"Taxi", "Taxi", "Taxi", "Такси"},
	{"Motocicleta", "Motorcycle", "Motocicleta", "Мотоцикл"},
	{"Vaixell", "Ship", "Barco", "Корабль"},
	{"Veler", "Sailboat", "Velero", "Парусник"},
	{"Avió", "Airplane", "Avión", "Самолёт"},
	{"Nedar", "To swim", "Nadar", "Плавать"},
	{"Conduir", "To drive", "Conducir", "Управлять"},
	{"Aeroport", "Airport", "Aeropuerto", "Аэропорт"},
	{"Port", "Port", "Puerto", "Порт"},
	{"Estació", "Station", "Estación", "Станция"},
	{"Barca", "Boat", "Barca", "Лодка"},
	{"Volar", "To fly", "Volar", "Летать"},
	{"Transbord", "Transfer", "Transbordo", "Пересадка"},
	{"Botiga", "Shop", "Tienda", "Магазин"},
	{"Farmàcia", "Pharmacy", "Farmacia", "Аптека"},
	{"Hospital", "Hospital", "Hospital", "Больница"},
	{"Restaurant", "Restaurant", "Restaurante", "Ресторан"},
	{"Banc", "Bank", "Banco", "Банк"},
	{"Hotel", "Hotel", "Hotel", "Отель"},
	{"Porta", "Door", "Puerta", "Дверь"},
	{"Finestra", "Window", "Ventana", "Окно"},
	{"Taula", "Table", "Mesa", "Стол"},
	{"Cadira", "Chair", "Silla", "Стул"},
	{"Llit", "Bed", "Cama", "Кровать"},
	{"Pa", "Bread", "Pan", "Хлеб"},
	{"Aigua", "Water", "Agua", "Вода"},
	{"Vi", "Wine", "Vino", "Вино"},
	{"Cervesa", "Beer", "Cerveza", "Пиво"},
	{"Te", "Tea", "Té", "Чай"},
	{"Suc", "Juice", "Zumo", "Сок"},
	{"Cafè", "Coffee", "Café", "Кофе"},
	{"Llet", "Milk", "Leche", "Молоко"},
	{"Poma", "Apple", "Manzana", "Яблоко"},
	{"Plàtan", "Banana", "Plátano", "Банан"},
	{"Tomàquet", "Tomato", "Tomate", "Помидор"},
	{"Patata", "Potato", "Patata", "Картошка"},
	{"Formatge", "Cheese", "Queso", "Сыр"},
	{"Carn", "Meat", "Carne", "Мясо"},
	{"Embotit", "Sausage", "Embutido", "Колбаса"},
	{"Salsitxes", "Sausages", "Salchichas", "Сосиски"},
	{"Peix", "Fish", "Pescado", "Рыба"},
	{"Pastís", "Cake", "Pastel", "Пирог"},
	{"Dolços", "Sweets", "Dulces", "Сладости"},
	{"Tassa", "Cup", "Taza", "Чашка"},
	{"Tetera", "Kettle", "Tetera", "Чайник"},
	{"Color", "Color", "Color", "Цвет"},
	{"Colors", "Colors", "Colores", "Цвета"},
	{"Vermell", "Red", "Rojo", "Красный"},
	{"Blau", "Blue", "Azul", "Синий"},
	{"Verd", "Green", "Verde", "Зелёный"},
	{"Groc", "Yellow", "Amarillo", "Жёлтый"},
	{"Blanc", "White", "Blanco", "Белый"},
	{"Negre", "Black", "Negro", "Чёрный"},
	{"Taronja", "Orange", "Naranja", "Оранжевый"},
	{"Rosa", "Pink", "Rosa", "Розовый"},
	{"Roba", "Clothes", "Ropa", "Одежда"},
	{"Traje", "Suit", "Traje", "Костюм"},
	{"Vestit", "Dress", "Vestido", "Платье"},
	{"Camisa", "Shirt", "Camisa", "Рубашка"},
	{"Faldilla", "Skirt", "Falda", "Юбка"},
	{"Jersei", "Sweater", "Jersey", "Кофта"},
	{"Abric", "Coat", "Abrigo", "Пальто"},
	{"Jaqueta", "Jacket", "Chaqueta", "Куртка"},
	{"Mitjons", "Socks", "Calcetines", "Носки"},
	{"Vols", "You want", "Quieres", "Ты хочешь"},
	{"Voleu", "You (pl.) want", "Queréis", "Вы хотите"},
	{"Alba", "Sunrise", "Amanecer", "Восход"},
	{"Posta de sol", "Sunset", "Puesta de sol", "Закат"},
	{"Sol", "Sun", "Sol", "Солнце"},
	{"Vent", "Wind", "Viento", "Ветер"},
	{"Núvol", "Cloud", "Nube", "Облако"},
	{"Fa calor", "It's hot", "Hace calor", "Жарко"},
	{"Fa fred", "It's cold", "Hace frío", "Холодно"},
	{"Pluja", "Rain", "Lluvia", "Дождь"},
	{"Plou", "It's raining", "Llueve", "Идет дождь"},
	{"Neu", "Snow", "Nieve", "Снег"},
	{"Neva", "It's snowing", "Nieva", "Идет снег"},
	{"Feina", "Work", "Trabajo", "Работа"},
	{"Treballo", "I work", "Trabajo", "Работаю"},
	{"Treballes", "You work", "Trabajas", "Работаешь"},
	{"Treballa", "He/she works", "Trabaja", "Работает"},
	{"Anar", "To go", "Ir", "Идти"},
	{"Menjar", "To eat", "Comer", "Есть"},
	{"Beure", "To drink", "Beber", "Пить"},
	{"Dormir", "To sleep", "Dormir", "Спать"},
	{"Llegir", "To read", "Leer", "Читать"},
	{"Parlar", "To speak", "Hablar", "Говорить"},
	{"Escoltar", "To listen", "Escuchar", "Слушать"},
	{"Veure", "To see", "Ver", "Видеть"},
	{"Estimar", "To love", "Amar", "Любить"},
	{"Comportar-se", "To behave", "Comportarse", "Вести себя"},
	{"Obrir", "To open", "Abrir", "Открывать"},
	{"Tancar", "To close", "Cerrar", "Закрывать"},
	{"Convidar", "To invite", "Invitar", "Приглашать"},
	{"Estar dret", "To stand", "Estar de pie", "Стоять"},
	{"Dreta", "Right", "Derecha", "Право"},
	{"A la dreta", "To the right", "A la derecha", "Направо"},
	{"Esquerra", "Left", "Izquierda", "Лево"},
	{"A l'esquerra", "To the left", "A la izquierda", "Налево"},
	{"Caminar", "To walk", "Caminar", "Ходить пешком"},
	{"Córrer", "To run", "Correr", "Бежать"},
	{"Paella", "Frying pan", "Sartén", "Сковорода"},
	{"Olla", "Pot", "Olla", "Кастрюля"},
	{"Cap", "Head", "Cabeza", "Голова"},
	{"Cara", "Face", "Cara", "Лицо"},
	{"Braç", "Arm", "Brazo", "Рука"},
	{"Cama", "Leg", "Pierna", "Нога"},
	{"Dit", "Finger", "Dedo", "Палец"},
	{"Estar malalt", "To be sick", "Estar enfermo", "Болеть"},
	{"Panxa", "Belly", "Barriga", "Живот"},
	{"Mareig", "Dizziness", "Mareo", "Головокружение"},
	{"Ordinador", "Computer", "Ordenador", "Компьютер"},
	{"Portàtil", "Laptop", "Portátil", "Ноутбук"},
	{"Ull", "Eye", "Ojo", "Глаз"},
	{"Nas", "Nose", "Nariz", "Нос"},
	{"Boca", "Mouth", "Boca", "Рот"},
	{"Orella", "Ear", "Oreja", "Ухо"},
	{"Esquena", "Back", "Espalda", "Спина"},
	{"Gran", "Big", "Grande", "Большой"},
	{"Petit", "Small", "Pequeño", "Маленький"},
	{"Calent", "Hot", "Caliente", "Горячий"},
	{"Fred", "Cold", "Frío", "Холодный"},
	{"Ràpid", "Fast", "Rápido", "Быстрый"},
	{"Lent", "Slow", "Lento", "Медленный"},
	{"Bonic", "Beautiful", "Bonito", "Красивый"},
	{"Vell", "Old", "Viejo", "Старый"},
	{"A", "In/At", "En/A", "В"},
	{"Sobre", "On", "Sobre", "На"},
	{"Sota", "Under", "Debajo", "Под"},
	{"Al costat", "Next to", "Al lado", "Рядом"},
	{"Entre", "Between", "Entre", "Между"},
}
